// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmos/crosschain/v1/query.proto

package crosschainv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName            = "/cosmos.crosschain.v1.Query/Params"
	Query_CrossChainPackage_FullMethodName = "/cosmos.crosschain.v1.Query/CrossChainPackage"
	Query_SendSequence_FullMethodName      = "/cosmos.crosschain.v1.Query/SendSequence"
	Query_ReceiveSequence_FullMethodName   = "/cosmos.crosschain.v1.Query/ReceiveSequence"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the total set of cross chain parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// CrossChainPackage returns the specified cross chain package
	CrossChainPackage(ctx context.Context, in *QueryCrossChainPackageRequest, opts ...grpc.CallOption) (*QueryCrossChainPackageResponse, error)
	// SendSequence returns the send sequence of the channel
	SendSequence(ctx context.Context, in *QuerySendSequenceRequest, opts ...grpc.CallOption) (*QuerySendSequenceResponse, error)
	// ReceiveSequence returns the receive sequence of the channel
	ReceiveSequence(ctx context.Context, in *QueryReceiveSequenceRequest, opts ...grpc.CallOption) (*QueryReceiveSequenceResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CrossChainPackage(ctx context.Context, in *QueryCrossChainPackageRequest, opts ...grpc.CallOption) (*QueryCrossChainPackageResponse, error) {
	out := new(QueryCrossChainPackageResponse)
	err := c.cc.Invoke(ctx, Query_CrossChainPackage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SendSequence(ctx context.Context, in *QuerySendSequenceRequest, opts ...grpc.CallOption) (*QuerySendSequenceResponse, error) {
	out := new(QuerySendSequenceResponse)
	err := c.cc.Invoke(ctx, Query_SendSequence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReceiveSequence(ctx context.Context, in *QueryReceiveSequenceRequest, opts ...grpc.CallOption) (*QueryReceiveSequenceResponse, error) {
	out := new(QueryReceiveSequenceResponse)
	err := c.cc.Invoke(ctx, Query_ReceiveSequence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params returns the total set of cross chain parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// CrossChainPackage returns the specified cross chain package
	CrossChainPackage(context.Context, *QueryCrossChainPackageRequest) (*QueryCrossChainPackageResponse, error)
	// SendSequence returns the send sequence of the channel
	SendSequence(context.Context, *QuerySendSequenceRequest) (*QuerySendSequenceResponse, error)
	// ReceiveSequence returns the receive sequence of the channel
	ReceiveSequence(context.Context, *QueryReceiveSequenceRequest) (*QueryReceiveSequenceResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) CrossChainPackage(context.Context, *QueryCrossChainPackageRequest) (*QueryCrossChainPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrossChainPackage not implemented")
}
func (UnimplementedQueryServer) SendSequence(context.Context, *QuerySendSequenceRequest) (*QuerySendSequenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSequence not implemented")
}
func (UnimplementedQueryServer) ReceiveSequence(context.Context, *QueryReceiveSequenceRequest) (*QueryReceiveSequenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveSequence not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CrossChainPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCrossChainPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CrossChainPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CrossChainPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CrossChainPackage(ctx, req.(*QueryCrossChainPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SendSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySendSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SendSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SendSequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SendSequence(ctx, req.(*QuerySendSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReceiveSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReceiveSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReceiveSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ReceiveSequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReceiveSequence(ctx, req.(*QueryReceiveSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.crosschain.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CrossChainPackage",
			Handler:    _Query_CrossChainPackage_Handler,
		},
		{
			MethodName: "SendSequence",
			Handler:    _Query_SendSequence_Handler,
		},
		{
			MethodName: "ReceiveSequence",
			Handler:    _Query_ReceiveSequence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/crosschain/v1/query.proto",
}
