// Since: cosmos-sdk 0.47

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmos/crosschain/v1/tx.proto

package crosschainv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName             = "/cosmos.crosschain.v1.Msg/UpdateParams"
	Msg_UpdateChannelPermissions_FullMethodName = "/cosmos.crosschain.v1.Msg/UpdateChannelPermissions"
	Msg_MintModuleTokens_FullMethodName         = "/cosmos.crosschain.v1.Msg/MintModuleTokens"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a governance operation for updating the x/crosschain module parameters.
	// The authority is defined in the keeper.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// UpdateChannelPermissions defines a governance operation for updating the channel permissions.
	// The authority is defined in the keeper.
	UpdateChannelPermissions(ctx context.Context, in *MsgUpdateChannelPermissions, opts ...grpc.CallOption) (*MsgUpdateChannelPermissionsResponse, error)
	// MintModuleTokens defines a governance operation for minting tokens for the crosschain module.
	// The authority is defined in the keeper.
	MintModuleTokens(ctx context.Context, in *MsgMintModuleTokens, opts ...grpc.CallOption) (*MsgMintModuleTokensResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateChannelPermissions(ctx context.Context, in *MsgUpdateChannelPermissions, opts ...grpc.CallOption) (*MsgUpdateChannelPermissionsResponse, error) {
	out := new(MsgUpdateChannelPermissionsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateChannelPermissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MintModuleTokens(ctx context.Context, in *MsgMintModuleTokens, opts ...grpc.CallOption) (*MsgMintModuleTokensResponse, error) {
	out := new(MsgMintModuleTokensResponse)
	err := c.cc.Invoke(ctx, Msg_MintModuleTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a governance operation for updating the x/crosschain module parameters.
	// The authority is defined in the keeper.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// UpdateChannelPermissions defines a governance operation for updating the channel permissions.
	// The authority is defined in the keeper.
	UpdateChannelPermissions(context.Context, *MsgUpdateChannelPermissions) (*MsgUpdateChannelPermissionsResponse, error)
	// MintModuleTokens defines a governance operation for minting tokens for the crosschain module.
	// The authority is defined in the keeper.
	MintModuleTokens(context.Context, *MsgMintModuleTokens) (*MsgMintModuleTokensResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) UpdateChannelPermissions(context.Context, *MsgUpdateChannelPermissions) (*MsgUpdateChannelPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChannelPermissions not implemented")
}
func (UnimplementedMsgServer) MintModuleTokens(context.Context, *MsgMintModuleTokens) (*MsgMintModuleTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintModuleTokens not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateChannelPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateChannelPermissions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateChannelPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateChannelPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateChannelPermissions(ctx, req.(*MsgUpdateChannelPermissions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MintModuleTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintModuleTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintModuleTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MintModuleTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintModuleTokens(ctx, req.(*MsgMintModuleTokens))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.crosschain.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "UpdateChannelPermissions",
			Handler:    _Msg_UpdateChannelPermissions_Handler,
		},
		{
			MethodName: "MintModuleTokens",
			Handler:    _Msg_MintModuleTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/crosschain/v1/tx.proto",
}
