run:
  tests: false
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  issues-exit-code: 1
  skip-files:
    - server/grpc/gogoreflection/serverreflection.go

linters:
  disable-all: true
  enable:
    - govet
      - errcheck
      - staticcheck
      - gosimple
      - structcheck
      - unused
      - deadcode

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - text: "SA1019: errors"
      linters:
        - staticcheck
    - text: "SA1019: sdkerr"
      linters:
        - staticcheck
    - text: "SA1019: sdkerrors"
      linters:
        - staticcheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  errcheck:
    check-type-assertions: false
  unused:
    check-exported: false
  govet:
    enable:
      - all
    disable:
      - shadow
      - fieldalignment
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  gocritic:
    disabled-checks:
      - appendAssign
      - unnecessaryDefer
  staticcheck:
    checks: [ 'all', '-ST1000', '-ST1003' ]
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
