run:
  tests: false
  timeout: 5m
  skip-files:
    - server/grpc/gogoreflection/serverreflection.go

linters:
  disable-all: true
  enable:
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - ineffassign
    - nolintlint
    - staticcheck
    - stylecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    - text: "ST1016:"
      linters:
        - stylecheck
    - text: "SA1019: errors"
      linters:
        - staticcheck
    - text: "SA1019: sdkerr"
      linters:
        - staticcheck
    - text: "SA1019: sdkerrors"
      linters:
        - staticcheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck
    - text: "typecheck"
      linters:
        - typecheck

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false