// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/feehub/v1alpha1/feehub.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the feehub module.
type Params struct {
	MaxTxSize       uint64 `protobuf:"varint,1,opt,name=max_tx_size,json=maxTxSize,proto3" json:"max_tx_size,omitempty"`
	MinGasPerByte   uint64 `protobuf:"varint,2,opt,name=min_gas_per_byte,json=minGasPerByte,proto3" json:"min_gas_per_byte,omitempty"`
	MsgSendGas      uint64 `protobuf:"varint,3,opt,name=msg_send_gas,json=msgSendGas,proto3" json:"msg_send_gas,omitempty"`
	MsgMultiSendGas uint64 `protobuf:"varint,4,opt,name=msg_multi_send_gas,json=msgMultiSendGas,proto3" json:"msg_multi_send_gas,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93836928b503a00, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxTxSize() uint64 {
	if m != nil {
		return m.MaxTxSize
	}
	return 0
}

func (m *Params) GetMinGasPerByte() uint64 {
	if m != nil {
		return m.MinGasPerByte
	}
	return 0
}

func (m *Params) GetMsgSendGas() uint64 {
	if m != nil {
		return m.MsgSendGas
	}
	return 0
}

func (m *Params) GetMsgMultiSendGas() uint64 {
	if m != nil {
		return m.MsgMultiSendGas
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.feehub.v1alpha1.Params")
}

func init() {
	proto.RegisterFile("cosmos/feehub/v1alpha1/feehub.proto", fileDescriptor_e93836928b503a00)
}

var fileDescriptor_e93836928b503a00 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3f, 0x4f, 0xc2, 0x40,
	0x18, 0xc6, 0x7b, 0x4a, 0x88, 0x9c, 0x22, 0x5a, 0x8d, 0x21, 0x0e, 0xad, 0xd1, 0xc5, 0xc4, 0x40,
	0x25, 0x6e, 0x4c, 0x86, 0xc4, 0x30, 0x35, 0x21, 0xe0, 0xe4, 0x72, 0x39, 0xe0, 0x3c, 0x2e, 0x72,
	0xbd, 0xa6, 0xef, 0x61, 0x0a, 0x9f, 0xc2, 0xd1, 0x91, 0x8f, 0xe3, 0xc8, 0xe8, 0xd4, 0x98, 0x63,
	0x71, 0xf5, 0x1b, 0x98, 0x96, 0xd6, 0x3f, 0xd3, 0x3d, 0xef, 0x7b, 0xcf, 0xef, 0x1d, 0x7e, 0xf8,
	0x62, 0xa4, 0x40, 0x2a, 0xf0, 0x1e, 0x19, 0x9b, 0xcc, 0x86, 0xde, 0x73, 0x8b, 0x4e, 0xc3, 0x09,
	0x6d, 0xe5, 0x73, 0x33, 0x8c, 0x94, 0x56, 0xf6, 0xc9, 0xa6, 0xd4, 0xcc, 0x97, 0x45, 0xe9, 0xf4,
	0x98, 0x2b, 0xae, 0xb2, 0x8a, 0x97, 0xa6, 0x4d, 0xfb, 0xfc, 0x0b, 0xe1, 0x72, 0x8f, 0x46, 0x54,
	0x82, 0xdd, 0xc0, 0xbb, 0x92, 0xc6, 0x44, 0xc7, 0x04, 0xc4, 0x82, 0xd5, 0xd1, 0x19, 0xba, 0x2c,
	0x75, 0xaa, 0x26, 0x71, 0x2b, 0x3e, 0x8d, 0xef, 0xe3, 0x81, 0x58, 0xb0, 0x7e, 0x45, 0x16, 0xd1,
	0x6e, 0xe3, 0x03, 0x29, 0x02, 0xc2, 0x29, 0x90, 0x90, 0x45, 0x64, 0x38, 0xd7, 0xac, 0xbe, 0x95,
	0x31, 0x87, 0x26, 0x71, 0xab, 0xbe, 0x08, 0xba, 0x14, 0x7a, 0x2c, 0xea, 0xcc, 0x35, 0xeb, 0x57,
	0xe5, 0xdf, 0xd1, 0xbe, 0xc6, 0x7b, 0x12, 0x38, 0x01, 0x16, 0x8c, 0xd3, 0x03, 0xf5, 0xed, 0x8c,
	0xdb, 0x37, 0x89, 0x8b, 0x7d, 0xe0, 0x03, 0x16, 0x8c, 0xbb, 0x14, 0xfa, 0x58, 0xfe, 0x64, 0xfb,
	0x16, 0xdb, 0x29, 0x21, 0x67, 0x53, 0x2d, 0x7e, 0xb9, 0x52, 0xc6, 0x1d, 0x99, 0xc4, 0xad, 0xf9,
	0xc0, 0xfd, 0xf4, 0xb3, 0x80, 0x6b, 0xf2, 0xff, 0xa2, 0xbd, 0xf3, 0xba, 0x74, 0xad, 0xcf, 0xa5,
	0x8b, 0x3a, 0x77, 0x6f, 0xc6, 0x41, 0x2b, 0xe3, 0xa0, 0x0f, 0xe3, 0xa0, 0x97, 0xb5, 0x63, 0xad,
	0xd6, 0x8e, 0xf5, 0xbe, 0x76, 0xac, 0x87, 0x2b, 0x2e, 0x74, 0x2a, 0x6d, 0xa4, 0xa4, 0x97, 0xbb,
	0xde, 0x3c, 0x0d, 0x18, 0x3f, 0x79, 0x71, 0x21, 0x5e, 0xcf, 0x43, 0x06, 0xc3, 0x72, 0x66, 0xf0,
	0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xea, 0xac, 0x64, 0x72, 0x96, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxTxSize != that1.MaxTxSize {
		return false
	}
	if this.MinGasPerByte != that1.MinGasPerByte {
		return false
	}
	if this.MsgSendGas != that1.MsgSendGas {
		return false
	}
	if this.MsgMultiSendGas != that1.MsgMultiSendGas {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MsgMultiSendGas != 0 {
		i = encodeVarintFeehub(dAtA, i, uint64(m.MsgMultiSendGas))
		i--
		dAtA[i] = 0x20
	}
	if m.MsgSendGas != 0 {
		i = encodeVarintFeehub(dAtA, i, uint64(m.MsgSendGas))
		i--
		dAtA[i] = 0x18
	}
	if m.MinGasPerByte != 0 {
		i = encodeVarintFeehub(dAtA, i, uint64(m.MinGasPerByte))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxTxSize != 0 {
		i = encodeVarintFeehub(dAtA, i, uint64(m.MaxTxSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeehub(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeehub(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxTxSize != 0 {
		n += 1 + sovFeehub(uint64(m.MaxTxSize))
	}
	if m.MinGasPerByte != 0 {
		n += 1 + sovFeehub(uint64(m.MinGasPerByte))
	}
	if m.MsgSendGas != 0 {
		n += 1 + sovFeehub(uint64(m.MsgSendGas))
	}
	if m.MsgMultiSendGas != 0 {
		n += 1 + sovFeehub(uint64(m.MsgMultiSendGas))
	}
	return n
}

func sovFeehub(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeehub(x uint64) (n int) {
	return sovFeehub(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeehub
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTxSize", wireType)
			}
			m.MaxTxSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeehub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTxSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasPerByte", wireType)
			}
			m.MinGasPerByte = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeehub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinGasPerByte |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgSendGas", wireType)
			}
			m.MsgSendGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeehub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgSendGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgMultiSendGas", wireType)
			}
			m.MsgMultiSendGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeehub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgMultiSendGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeehub(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeehub
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeehub(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeehub
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeehub
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeehub
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeehub
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeehub
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeehub
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeehub        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeehub          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeehub = fmt.Errorf("proto: unexpected end of group")
)
