// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/oracle/v1/event.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventPackageClaim is emitted when a cross chain package is processed
type EventPackageClaim struct {
	SrcChainId      uint32 `protobuf:"varint,1,opt,name=src_chain_id,json=srcChainId,proto3" json:"src_chain_id,omitempty"`
	DestChainId     uint32 `protobuf:"varint,2,opt,name=dest_chain_id,json=destChainId,proto3" json:"dest_chain_id,omitempty"`
	ChannelId       uint32 `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PackageType     uint32 `protobuf:"varint,4,opt,name=package_type,json=packageType,proto3" json:"package_type,omitempty"`
	ReceiveSequence uint64 `protobuf:"varint,5,opt,name=receive_sequence,json=receiveSequence,proto3" json:"receive_sequence,omitempty"`
	SendSequence    int64  `protobuf:"varint,6,opt,name=send_sequence,json=sendSequence,proto3" json:"send_sequence,omitempty"`
	Crash           bool   `protobuf:"varint,7,opt,name=crash,proto3" json:"crash,omitempty"`
	ErrorMsg        string `protobuf:"bytes,8,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	SynRelayFee     string `protobuf:"bytes,9,opt,name=syn_relay_fee,json=synRelayFee,proto3" json:"syn_relay_fee,omitempty"`
	AckRelayFee     string `protobuf:"bytes,10,opt,name=ack_relay_fee,json=ackRelayFee,proto3" json:"ack_relay_fee,omitempty"`
}

func (m *EventPackageClaim) Reset()         { *m = EventPackageClaim{} }
func (m *EventPackageClaim) String() string { return proto.CompactTextString(m) }
func (*EventPackageClaim) ProtoMessage()    {}
func (*EventPackageClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e254cedc4112fb0, []int{0}
}
func (m *EventPackageClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPackageClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPackageClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPackageClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPackageClaim.Merge(m, src)
}
func (m *EventPackageClaim) XXX_Size() int {
	return m.Size()
}
func (m *EventPackageClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPackageClaim.DiscardUnknown(m)
}

var xxx_messageInfo_EventPackageClaim proto.InternalMessageInfo

func (m *EventPackageClaim) GetSrcChainId() uint32 {
	if m != nil {
		return m.SrcChainId
	}
	return 0
}

func (m *EventPackageClaim) GetDestChainId() uint32 {
	if m != nil {
		return m.DestChainId
	}
	return 0
}

func (m *EventPackageClaim) GetChannelId() uint32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *EventPackageClaim) GetPackageType() uint32 {
	if m != nil {
		return m.PackageType
	}
	return 0
}

func (m *EventPackageClaim) GetReceiveSequence() uint64 {
	if m != nil {
		return m.ReceiveSequence
	}
	return 0
}

func (m *EventPackageClaim) GetSendSequence() int64 {
	if m != nil {
		return m.SendSequence
	}
	return 0
}

func (m *EventPackageClaim) GetCrash() bool {
	if m != nil {
		return m.Crash
	}
	return false
}

func (m *EventPackageClaim) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *EventPackageClaim) GetSynRelayFee() string {
	if m != nil {
		return m.SynRelayFee
	}
	return ""
}

func (m *EventPackageClaim) GetAckRelayFee() string {
	if m != nil {
		return m.AckRelayFee
	}
	return ""
}

func init() {
	proto.RegisterType((*EventPackageClaim)(nil), "cosmos.oracle.v1.EventPackageClaim")
}

func init() { proto.RegisterFile("cosmos/oracle/v1/event.proto", fileDescriptor_3e254cedc4112fb0) }

var fileDescriptor_3e254cedc4112fb0 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd1, 0xcd, 0x4e, 0xab, 0x40,
	0x14, 0xc0, 0xf1, 0x4e, 0xbf, 0x6e, 0x99, 0xb6, 0xb9, 0x95, 0xb8, 0x20, 0x51, 0x09, 0xd6, 0x0d,
	0xc6, 0x08, 0x69, 0x7c, 0x03, 0x9b, 0x9a, 0x74, 0x61, 0x62, 0xd0, 0x95, 0x1b, 0x32, 0x1d, 0x8e,
	0x40, 0x80, 0x01, 0x67, 0x28, 0x91, 0xb7, 0xf0, 0xb1, 0x5c, 0x76, 0xe9, 0xd2, 0xb4, 0x89, 0xcf,
	0x61, 0x06, 0xa8, 0x75, 0x45, 0xf8, 0x9f, 0x5f, 0x20, 0x33, 0x07, 0x9f, 0xd2, 0x54, 0x24, 0xa9,
	0xb0, 0x53, 0x4e, 0x68, 0x0c, 0x76, 0x31, 0xb3, 0xa1, 0x00, 0x96, 0x5b, 0x19, 0x4f, 0xf3, 0x54,
	0x9d, 0xd4, 0x53, 0xab, 0x9e, 0x5a, 0xc5, 0x6c, 0xfa, 0xdd, 0xc6, 0x47, 0x0b, 0x29, 0x1e, 0x08,
	0x8d, 0x88, 0x0f, 0xf3, 0x98, 0x84, 0x89, 0x6a, 0xe0, 0x91, 0xe0, 0xd4, 0xa5, 0x01, 0x09, 0x99,
	0x1b, 0x7a, 0x1a, 0x32, 0x90, 0x39, 0x76, 0xb0, 0xe0, 0x74, 0x2e, 0xd3, 0xd2, 0x53, 0xa7, 0x78,
	0xec, 0x81, 0xc8, 0x0f, 0xa4, 0x5d, 0x91, 0xa1, 0x8c, 0x7b, 0x73, 0x86, 0x31, 0x0d, 0x08, 0x63,
	0x10, 0x4b, 0xd0, 0xa9, 0x80, 0xd2, 0x94, 0xa5, 0xa7, 0x9e, 0xe3, 0x51, 0x56, 0xff, 0xd4, 0xcd,
	0xcb, 0x0c, 0xb4, 0x6e, 0xfd, 0x85, 0xa6, 0x3d, 0x95, 0x19, 0xa8, 0x97, 0x78, 0xc2, 0x81, 0x42,
	0x58, 0x80, 0x2b, 0xe0, 0x75, 0x0d, 0x8c, 0x82, 0xd6, 0x33, 0x90, 0xd9, 0x75, 0xfe, 0x37, 0xfd,
	0xb1, 0xc9, 0xea, 0x05, 0x1e, 0x0b, 0x60, 0xde, 0xc1, 0xf5, 0x0d, 0x64, 0x76, 0x9c, 0x91, 0x8c,
	0xbf, 0xe8, 0x18, 0xf7, 0x28, 0x27, 0x22, 0xd0, 0xfe, 0x19, 0xc8, 0x1c, 0x38, 0xf5, 0x8b, 0x7a,
	0x82, 0x15, 0xe0, 0x3c, 0xe5, 0x6e, 0x22, 0x7c, 0x6d, 0x60, 0x20, 0x53, 0x71, 0x06, 0x55, 0xb8,
	0x17, 0xbe, 0x3c, 0xa8, 0x28, 0x99, 0xcb, 0x21, 0x26, 0xa5, 0xfb, 0x02, 0xa0, 0x29, 0x15, 0x18,
	0x8a, 0x92, 0x39, 0xb2, 0xdd, 0x01, 0x48, 0x43, 0x68, 0xf4, 0xc7, 0xe0, 0xda, 0x10, 0x1a, 0xed,
	0xcd, 0xed, 0xe2, 0x63, 0xab, 0xa3, 0xcd, 0x56, 0x47, 0x5f, 0x5b, 0x1d, 0xbd, 0xef, 0xf4, 0xd6,
	0x66, 0xa7, 0xb7, 0x3e, 0x77, 0x7a, 0xeb, 0xf9, 0xca, 0x0f, 0xf3, 0x60, 0xbd, 0xb2, 0x68, 0x9a,
	0xd8, 0xcd, 0xf6, 0xea, 0xc7, 0xb5, 0xf0, 0x22, 0xfb, 0x6d, 0xbf, 0x4a, 0x79, 0x47, 0x62, 0xd5,
	0xaf, 0x16, 0x79, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff, 0xec, 0xb3, 0x85, 0x18, 0xe8, 0x01, 0x00,
	0x00,
}

func (m *EventPackageClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPackageClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPackageClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AckRelayFee) > 0 {
		i -= len(m.AckRelayFee)
		copy(dAtA[i:], m.AckRelayFee)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.AckRelayFee)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.SynRelayFee) > 0 {
		i -= len(m.SynRelayFee)
		copy(dAtA[i:], m.SynRelayFee)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.SynRelayFee)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ErrorMsg) > 0 {
		i -= len(m.ErrorMsg)
		copy(dAtA[i:], m.ErrorMsg)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ErrorMsg)))
		i--
		dAtA[i] = 0x42
	}
	if m.Crash {
		i--
		if m.Crash {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.SendSequence != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.SendSequence))
		i--
		dAtA[i] = 0x30
	}
	if m.ReceiveSequence != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ReceiveSequence))
		i--
		dAtA[i] = 0x28
	}
	if m.PackageType != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.PackageType))
		i--
		dAtA[i] = 0x20
	}
	if m.ChannelId != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ChannelId))
		i--
		dAtA[i] = 0x18
	}
	if m.DestChainId != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.DestChainId))
		i--
		dAtA[i] = 0x10
	}
	if m.SrcChainId != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.SrcChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventPackageClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SrcChainId != 0 {
		n += 1 + sovEvent(uint64(m.SrcChainId))
	}
	if m.DestChainId != 0 {
		n += 1 + sovEvent(uint64(m.DestChainId))
	}
	if m.ChannelId != 0 {
		n += 1 + sovEvent(uint64(m.ChannelId))
	}
	if m.PackageType != 0 {
		n += 1 + sovEvent(uint64(m.PackageType))
	}
	if m.ReceiveSequence != 0 {
		n += 1 + sovEvent(uint64(m.ReceiveSequence))
	}
	if m.SendSequence != 0 {
		n += 1 + sovEvent(uint64(m.SendSequence))
	}
	if m.Crash {
		n += 2
	}
	l = len(m.ErrorMsg)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.SynRelayFee)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.AckRelayFee)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventPackageClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPackageClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPackageClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcChainId", wireType)
			}
			m.SrcChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcChainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChainId", wireType)
			}
			m.DestChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestChainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			m.ChannelId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChannelId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageType", wireType)
			}
			m.PackageType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PackageType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiveSequence", wireType)
			}
			m.ReceiveSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiveSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendSequence", wireType)
			}
			m.SendSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendSequence |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Crash", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Crash = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SynRelayFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SynRelayFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckRelayFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AckRelayFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
