name: "Warn about consensus code changes"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: ["**/*.go"]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/bnb-chain
      GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
    # Skip draft PRs and PRs starting with: revert, test, chore, ci, docs, style, build, refactor
    if: "!github.event.pull_request.draft && !contains(github.event.pull_request.title, 'revert') && !contains(github.event.pull_request.title, 'test') && !contains(github.event.pull_request.title, 'chore') && !contains(github.event.pull_request.title, 'ci') && !contains(github.event.pull_request.title, 'docs') && !contains(github.event.pull_request.title, 'style') && !contains(github.event.pull_request.title, 'build') && !contains(github.event.pull_request.title, 'refactor')"
    steps:
      - uses: actions/checkout@v3
      - uses: orijtech/consensuswarn@main
        with:
          roots: 'github.com/cosmos/cosmos-sdk/baseapp.BaseApp.DeliverTx,github.com/cosmos/cosmos-sdk/baseapp.BaseApp.BeginBlock,github.com/cosmos/cosmos-sdk/baseapp.BaseApp.EndBlock,github.com/cosmos/cosmos-sdk/baseapp.BaseApp.Commit'
